import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { AuthProvider } from "@/components/auth-provider";
import { StreamProvider } from "@/components/stream-provider";
import { getSession, getUser } from "@/lib/supabase/server";
import { TRPCReactProvider } from "@/trpc/react";
import { NuqsAdapter } from "nuqs/adapters/next/app";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const { user } = await getUser();
  const { session } = await getSession();
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <AuthProvider user={user ?? undefined} session={session ?? undefined}>
            <StreamProvider>
              <NuqsAdapter>{children}</NuqsAdapter>
            </StreamProvider>
          </AuthProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
