export const homepageSlideshows = {
  brian: {
    short_summary:
      "Ah, the CEO who built an empire renting air mattresses while listening to Hotel California on repeat. Your playlist screams 'mid-life crisis meets tech millionaire trying to stay relatable'",
    music_taste_analysis_1:
      "The Eagles as your top artist? I guess when you're worth billions, you can afford to have the most basic taste possible",
    music_taste_analysis_2:
      "Your playlist is what happens when a Silicon Valley exec tries to convince people they're still down to earth",
    music_taste_analysis_3:
      "More acoustic guitars than a college freshman's dorm room. At least you're consistent with the bland.",
    lyric_therapy_needed:
      "You're listening to 'Take It Easy' while running a $86B company? The irony is thicker than your Series A pitch deck.",
    identity_crisis_level: {
      level: "SEVERE",
      description:
        "When your music taste is split between boomer rock and indie folk, it's clear you're still trying to figure out if you're a tech bro or a hippie",
    },
    emotional_stability_rating: {
      level: "42/100",
      description:
        "You've got more travel-themed playlists than actual vacation days. Compensating much for being chained to those board meetings?",
    },
    achievement: {
      title: "MASTER OF MEDIOCRITY",
      description:
        "Successfully collected every cliché road trip song known to mankind while pretending it's a personality trait",
    },
    dance_floor_credibility:
      "Your idea of dancing is probably swaying awkwardly to 'Yellow' at company retreats while employees pretend not to notice",
    song_you_would_hit_the_dance_floor:
      "'Margaritaville' - because nothing says 'I'm a fun CEO' like doing the dad shuffle to Jimmy Buffett while your employees film it for their private Slack channel",
    songs_you_secretly_think_are_about_you:
      "'Space Oddity' - Ground Control to Major Brian? You're floating in your tin can of success, but your music taste is still stuck on Earth",
    guilty_pleasure_song:
      "'I'm Yours' by Jason Mraz - Nothing says 'I peaked culturally in 2008' like secretly ukulele-ing to this in your Tesla",
    least_popular_artist:
      "Ah yes, Norah Jones - because nothing says 'I'm sophisticated' like the same music they play at Starbucks",
    most_popular_artist:
      "The Beatles? Wow, such an obscure choice. Next you'll tell me you've discovered this underground band called Queen",
    time_machine_status:
      "Your playlist suggests you're simultaneously stuck in the 60s, trying to be cool in the 2010s, and somehow still missing both marks completely",
    titles_that_need_therapy:
      "'Wanderlust Vibes'? 'Nomadic Spirit'? Your playlist names sound like they were generated by an AI trained on Instagram captions from 2015",
    final_diagnosis:
      "Chronic case of Silicon Valley Success Syndrome with acute symptoms of musical basic-ness. Treatment recommended: Actually living in a van down by the river instead of just singing about it",
    recommendation:
      "Maybe try listening to music made after 2015? Or just embrace being the guy who made billions while having the music taste of a retired geography teacher",
    top_artist_image_url:
      "https://www.thisdayinmusic.com/wp-content/uploads/2016/01/hotel-california.jpg",
    most_popular_artist_image_url:
      "https://upload.wikimedia.org/wikipedia/en/thumb/4/42/Beatles_-_Abbey_Road.jpg/220px-Beatles_-_Abbey_Road.jpg",
    least_popular_artist_image_url:
      "https://store.bluenote.com/cdn/shop/files/NJVisionscoverFinal.jpg?v=1705586453",
  },
  trump: {
    short_summary:
      "Looks like someone's trying to 'Make Music Great Again' with a playlist that screams 'I peaked in 1969' louder than your spray tan screams 'I peaked in general'",
    music_taste_analysis_1:
      "Frank Sinatra tops your list? Of course the guy who bankrupted casinos would idolize the Rat Pack.",
    music_taste_analysis_2:
      "Your playlists are like your policies - stuck in the past and making everyone uncomfortable.",
    music_taste_analysis_3:
      "Nothing says 'man of the people' like blasting Pavarotti at Mar-a-Lago.",
    lyric_therapy_needed:
      "'Losing My Religion' and 'Suspicious Minds' on repeat? Someone's projecting their legal troubles onto their playlist.",
    identity_crisis_level: {
      level: "CATASTROPHIC",
      description:
        "You're playing 'My Way' while simultaneously trying to be Elvis, Johnny Cash, AND a patriot. Pick a personality, any personality!",
    },
    emotional_stability_rating: {
      level: "13/100",
      description:
        "Playing 'Nothing Compares 2 U' while tweeting at 3 AM about election fraud isn't the flex you think it is.",
    },
    achievement: {
      title: "MASTER OF SELF-DELUSION",
      description:
        "Successfully convinced yourself that 'You Can't Always Get What You Want' isn't about your presidential terms",
    },
    dance_floor_credibility:
      "Your dancing looks like a malfunctioning wind-up toy having a seizure. Please stay seated during 'YMCA'.",
    song_you_would_hit_the_dance_floor:
      "'America, F**k Yeah!' - because nothing says 'presidential' like aggressively fist-pumping to a puppet movie soundtrack while your tie flaps in the wind",
    songs_you_secretly_think_are_about_you:
      "'It's a Man's Man's Man's World' - Bold choice for someone who got beaten by a woman in the popular vote. The irony is thicker than your combover.",
    guilty_pleasure_song:
      "'Hello' by Lionel Richie - You keep playing it while staring at your old Twitter account, don't you?",
    least_popular_artist:
      "Sinead O'Connor - Your Musical Hot Take that nobody asked for, just like your opinions on everything else.",
    most_popular_artist:
      "Frank Sinatra, because nothing says 'I'm totally not compensating' like obsessing over the original MAGA hat wearer",
    time_machine_status:
      "Stuck somewhere between Elvis's Las Vegas years and your own Vegas bankruptcy years. At least Elvis had an excuse - he was on drugs.",
    titles_that_need_therapy:
      "'DJ T's Mar-a-Lago Mix' sounds like what plays in an elevator to hell. 'Presidential Playlist' is just denial in audio form.",
    final_diagnosis:
      "Severe case of Musical Narcissistic Personality Disorder, complicated by chronic nostalgia and an inability to accept that 1969 is over.",
    recommendation:
      "Try listening to 'Jailhouse Rock' - consider it research for future accommodations.",
    top_artist_image_url:
      "https://d3i6fh83elv35t.cloudfront.net/newshour/app/uploads/2015/12/GettyImages-85339538-1024x889.jpg",
    most_popular_artist_image_url:
      "https://d3i6fh83elv35t.cloudfront.net/newshour/app/uploads/2015/12/GettyImages-85339538-1024x889.jpg",
    least_popular_artist_image_url:
      "https://media.newyorker.com/photos/5909771c2179605b11ad8664/3:4/w_1612,h_2149,c_limit/Petrusich-Sinead-OConnor.jpg",
  },
  elon: {
    short_summary:
      "Ah, the playlist of a billionaire who thinks he's David Bowie but comes off more like a mid-life crisis in space boots.",
    music_taste_analysis_1:
      "Your top artist is Monty Python? Well, your life IS a comedy sketch - just not the intentionally funny kind.",
    music_taste_analysis_2:
      "Nothing says 'trying too hard to be deep' like having both Pink Floyd AND your ex's entire discography.",
    music_taste_analysis_3:
      "Classical music doesn't make you sophisticated when you're tweeting memes between movements.",
    lyric_therapy_needed:
      "From 'Space Oddity' to 'Rocket Man' - we get it, you like space. But Ground Control to Major Ego: Earth needs you to calm down.",
    identity_crisis_level: {
      level: "ASTRONOMICAL",
      description:
        "Listening to both 'Always Look on the Bright Side of Life' and 'The Imperial March' - even your playlist can't decide if you're the hero or villain",
    },
    emotional_stability_rating: {
      level: "23/100",
      description:
        "You've got more Grimes songs than functioning Twitter servers. Someone's clearly not over their ex.",
    },
    achievement: {
      title: "MASTER OF MIDLIFE CRISIS",
      description:
        "Successfully combined classical masterpieces with ex-girlfriend tracks while running multiple companies into the ground",
    },
    dance_floor_credibility:
      "Your dance moves probably look like a Tesla on autopilot malfunctioning - best keep those feet grounded.",
    song_you_would_hit_the_dance_floor:
      "'Don't Stop Me Now' because like your Twitter acquisition, you just can't help making questionable decisions in public.",
    songs_you_secretly_think_are_about_you:
      "'Space Oddity' - because you think you're Major Tom but you're really just the tin can floating in space. At least Major Tom had better PR.",
    guilty_pleasure_song:
      "Every single Grimes song in your library. Nothing says 'I'm not over my ex' like obsessively streaming their entire discography while pretending to build AI.",
    least_popular_artist:
      "Bach? Really? Just because you named your kid X Æ A-12 doesn't mean you understand classical composition.",
    most_popular_artist:
      "Queen's 'Bohemian Rhapsody' on repeat - compensating for something with all those 'Galileo' parts?",
    time_machine_status:
      "Stuck between classical compositions and electronic beats like a DeLorean with a dead battery. Your music taste is as confused as your cryptocurrency tweets.",
    titles_that_need_therapy:
      "'Rock Classics' and 'Humorous and Inspirational Tunes' - your playlist names are as basic as your understanding of public transportation.",
    final_diagnosis:
      "Severe case of Main Character Syndrome complicated by space obsession and unresolved ex issues. Prognosis: Terminal try-hard.",
    recommendation:
      "Maybe spend less time curating playlists and more time learning how to run the companies you keep buying. Also, therapy. Lots of therapy.",
    top_artist_image_url:
      "https://platform.polygon.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/20018845/seeso_Monty_Python_And_The_Holy_Grail_Mov_Full_Image_GalleryBackground_en_US_1483993549331._RI_.jpg?quality=90&strip=all&crop=21.875,0,56.25,100",
    most_popular_artist_image_url:
      "https://assets.soundgym.co/posts/9UECJ9.jpg",
    least_popular_artist_image_url:
      "https://hips.hearstapps.com/hmg-prod/images/johann-sebastian-bach-gettyimages-51246888.jpg?crop=1xw:0.74971450323563xh;center,top&resize=1200:*",
  },
  kanye: {
    short_summary:
      "Congratulations! You've achieved peak narcissism by exclusively listening to yourself. At least you're consistent with your god complex.",
    music_taste_analysis_1:
      "Wow, your top artist is... yourself. Shocking. I guess nobody else can match your 'genius' level, right Ye?",
    music_taste_analysis_2:
      "Your playlist names scream 'I need validation' louder than your tweets about running for president.",
    music_taste_analysis_3:
      "From College Dropout to Gospel - the musical equivalent of having multiple personality disorder.",
    lyric_therapy_needed:
      "'I am a God' isn't just a song title, it's your daily affirmation. Maybe time to book some sessions with an actual therapist?",
    identity_crisis_level: {
      level: "ASTRONOMICAL",
      description:
        "You went from 'Jesus Walks' to 'I Am a God' to 'Ultralight Beam'. Pick a lane, preferably one that doesn't involve comparing yourself to deities.",
    },
    emotional_stability_rating: {
      level: "23/100",
      description:
        "Your playlist jumps from 'Power' to 'Runaway' to 'All of the Lights' faster than your mood swings on Twitter. That's concerning.",
    },
    achievement: {
      title: "MASTER OF SELF-OBSESSION",
      description:
        "Successfully created and listened to more songs about yourself than any other artist in history. Congratulations?",
    },
    dance_floor_credibility:
      "About as credible as your 2020 presidential campaign. Stick to the studio.",
    song_you_would_hit_the_dance_floor:
      "'Stronger' - because nothing says 'I'm compensating' like dancing to your own Daft Punk remix while screaming 'that that don't kill me can only make me stronger!'",
    songs_you_secretly_think_are_about_you:
      "'I Am a God' - because subtlety isn't your strong suit. You probably wake up every morning, look in the mirror, and blast this while practicing your messiah pose.",
    guilty_pleasure_song:
      "'Gold Digger' - The irony of you singing about gold diggers while paying $200k/month in alimony is *chef's kiss*",
    least_popular_artist:
      "New Slang? More like New Flop. Even your hardcore fans pretend this one doesn't exist.",
    most_popular_artist:
      "Yourself. Because of course it is. Your ego wouldn't have it any other way.",
    time_machine_status:
      "Stuck between 2004's 'humble' College Dropout era and whatever messianic era you're currently in. It's like watching someone's entire quarter-life crisis on shuffle.",
    titles_that_need_therapy:
      "'Yeezus' Dark Tracks', 'Soul of Ye', 'West World' - your playlist names sound like chapter titles from a narcissist's autobiography.",
    final_diagnosis:
      "Severe case of main character syndrome complicated by chronic self-sampling and acute god complex. Prognosis: Terminal uniqueness.",
    recommendation:
      "Consider listening to literally anyone else's music. Maybe start a playlist called 'Songs Not About Me' - it'll be a challenge, but I believe in you.",
    top_artist_image_url:
      "https://ew.com/thmb/1qOQY-fHmKznauBqAZXTyPswhIY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Kanye-West-9187f0273e7e43a2866b6ec2b5aa7ae2.jpg",
    most_popular_artist_image_url:
      "https://ew.com/thmb/1qOQY-fHmKznauBqAZXTyPswhIY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Kanye-West-9187f0273e7e43a2866b6ec2b5aa7ae2.jpg",
    least_popular_artist_image_url:
      "https://i.ytimg.com/vi/zYwCmcB0XMw/hqdefault.jpg",
  },
  sam: {
    short_summary:
      "Ah, the Silicon Valley's most pretentious playlist curator! Your music taste screams 'I think I'm too intellectual for lyrics' while secretly practicing robot dance moves to Daft Punk in your office.",
    music_taste_analysis_1:
      "Max Richter? Really? Nothing says 'I'm a tech CEO with an existential crisis' quite like recomposed classical music.",
    music_taste_analysis_2:
      "Your playlist is what an AI would create if you asked it to 'make music that sounds important'.",
    music_taste_analysis_3:
      "More instrumental tracks than a dentist's waiting room. At least your AI won't interrupt the background music.",
    lyric_therapy_needed:
      "When your most emotional song is literally called 'An Ending', you might want to talk to someone about that. And not ChatGPT.",
    identity_crisis_level: {
      level: "CATASTROPHIC",
      description:
        "You're listening to 'Robot Rock' while trying to convince the world AI won't replace humans. The irony is delicious.",
    },
    emotional_stability_rating: {
      level: "23/100",
      description:
        "Your playlists are named things like 'Machine Minds and Electronic Rhythms'. You're one Hans Zimmer track away from a supervillain origin story.",
    },
    achievement: {
      title: "MOST PRETENTIOUS PLAYLIST CURATOR 2024",
      description:
        "Successfully created playlists that make even classical music sound like a tech startup pitch deck",
    },
    dance_floor_credibility:
      "The only dancing you should do is the nervous shuffle at Congressional hearings about AI safety.",
    song_you_would_hit_the_dance_floor:
      "'Computer World' by Kraftwerk, but only because you think it's a PowerPoint presentation about binary code.",
    songs_you_secretly_think_are_about_you:
      "'Time' by Hans Zimmer - because nothing says 'I think I'm saving humanity' quite like dramatic orchestral swells while coding.",
    guilty_pleasure_song:
      "'Robot Rock' by Daft Punk - You probably think it's a documentary about OpenAI's workplace culture.",
    least_popular_artist:
      "The Glitch Mob - Your hot take on experimental electronic music that nobody asked for, just like your opinions on cryptocurrency.",
    most_popular_artist:
      "Hans Zimmer - Because apparently even your background music needs to feel like you're making world-changing decisions.",
    time_machine_status:
      "Stuck between pretending to appreciate 18th-century classical music and trying to sound futuristic with electronic beats. The present just isn't dramatic enough for you, is it?",
    titles_that_need_therapy:
      "'Machine Minds and Electronic Rhythms'? 'AI & Tech: A Soundscape'? Your playlist titles sound like rejected Black Mirror episodes.",
    final_diagnosis:
      "Severe case of Silicon Valley Protagonist Syndrome, complicated by an addiction to dramatic background music and an allergic reaction to lyrics.",
    recommendation:
      "Try listening to music with actual words sometimes. Maybe start with 'Help!' by The Beatles - seems appropriate.",
    top_artist_image_url:
      "https://images.squarespace-cdn.com/content/v1/5745d9f137013b9d0a627c60/1682149408814-OZKE3ZBJH7EJ64G7TMSA/max-richter-the-creative-process-podcast-SQ.jpg?format=1500w",
    most_popular_artist_image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRh_z7Y9bjWL__fUbn3vDeVvktMQc0p_xPuGg&s",
    least_popular_artist_image_url:
      "https://travel.home.sndimg.com/content/dam/images/travel/fullrights/2018/6/25/Original_Jessica-Yonker_Bonnaroo-Arts-Music-Festival-2018_Glitch-Mob.jpg.rend.hgtvcom.616.462.suffix/1529947735886.jpeg",
  },
  taylor: {
    short_summary:
      "Ah, Taylor Swift - the queen of turning every minor inconvenience into a chart-topping breakup song while cosplaying as different music genres.",
    music_taste_analysis_1:
      "Your top artist is Taylor Swift? Shocking. I bet you also think pizza is an adventurous food choice.",
    music_taste_analysis_2:
      "Mixing indie with mainstream pop like you're trying to convince people you're 'not like other girls'",
    music_taste_analysis_3:
      "From country to pop to indie folk - identity crisis much? Pick a lane, sweetie.",
    lyric_therapy_needed:
      "With playlists named 'Heartfelt Tunes' and 'Reflective Sounds', you're one breakup away from writing your own version of 'All Too Well'",
    identity_crisis_level: {
      level: "SEVERE",
      description:
        "Bouncing between The Lumineers and Kendrick Lamar like a musical pinball machine having an existential breakdown",
    },
    emotional_stability_rating: {
      level: "23/100",
      description:
        "Listening to 'People, I've Been Sad' while creating playlists called 'Reflective Sounds'? Your therapist deserves a raise.",
    },
    achievement: {
      title: "MASTER OF MUSICAL MOOD SWINGS",
      description:
        "Successfully convinced yourself that every sad indie song is about your life while maintaining a playlist called 'Playlist by ME!'",
    },
    dance_floor_credibility:
      "With 'Ho Hey' as your most played track, please stay at least 50 feet away from any dance floor",
    song_you_would_hit_the_dance_floor:
      "'Pumped Up Kicks' - because nothing says 'I can't dance' like awkwardly swaying to a song about dark themes while thinking it's just a catchy tune",
    songs_you_secretly_think_are_about_you:
      "'The Man' by Taylor Swift - because obviously YOU could be the CEO if it weren't for the patriarchy, right? Meanwhile, you can't even decide on a consistent music genre.",
    guilty_pleasure_song:
      "'Everybody' by Martin Solveig - trying to convince yourself you understand European electronic music while secretly dancing to it alone in your room like a possessed windmill",
    least_popular_artist:
      "Oh, you listen to LUME? Please tell us more about how you 'discovered' them before they were cool, you musical Christopher Columbus",
    most_popular_artist:
      "Taylor Swift - congratulations on having the most basic taste possible. You probably think being a Swiftie is a personality trait",
    time_machine_status:
      "Jumping from Joni Mitchell's 1971 to Taylor Swift's 2019 like you're Doctor Who with an identity crisis and a Spotify subscription",
    titles_that_need_therapy:
      "'Playlist by ME!' - we get it, you think you're the main character. 'Heartfelt Tunes' and 'Reflective Sounds'? Your playlists sound like rejected self-help book titles",
    final_diagnosis:
      "Chronic Main Character Syndrome complicated by severe genre-hopping and an unhealthy obsession with Taylor Swift's dating history",
    recommendation:
      "Try listening to something that isn't about breakups or feeling misunderstood. Maybe some white noise? It might be less emotionally damaging.",
    top_artist_image_url:
      "https://upload.wikimedia.org/wikipedia/en/1/1f/Taylor_Swift_-_Taylor_Swift.png",
    most_popular_artist_image_url:
      "https://upload.wikimedia.org/wikipedia/en/1/1f/Taylor_Swift_-_Taylor_Swift.png",
    least_popular_artist_image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDktOlAniJYGUbbIVgCiV6-lwkj-rWXD79Lg&s",
  },
};
